spring:
  security:
    oauth2:
      client:
        registration:
          gitlab:
            client-id: 076f9e789fac2f361c2e0145aa0cc7298cd6c5455492f3c90999480e40406d3f
            client-secret: gloas-2b635dc4bf910399e28ed5ede32d88305bc7ebf6450150ee8a3cac4078fecf91
            scope: openid+profile+email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/gitlab
        provider:
          gitlab:
            issuer-uri: https://gitlab.com
            user-name-attribute: sub
google-cloud:
  coupon-info:
    url: "https://gcp.secure.force.com/GCPEDU?cid=aI5UzI3bVzR2nTsBmskT9XAmH0pDNXJrLigkvt1bnJOxPyg2Ez%2FPtyq%2FEpjU5Ja0/"
    request-info:
      details: "You will be asked for a name and email address, which needs to match your school domain. A confirmation email will be sent to you with a coupon code."
    request-until: "3/6/2025"
    coupon-valid-until: "11/6/2025"
    note: "You can only request ONE code per unique email address."